name: courseswap
description: A platform for students to exchange courses or exam slots.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  dio: ^5.0.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0 
  build_runner: ^2.4.4 

flutter:
  uses-material-design: true