version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: courseswap_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/courseswap
      - REDIS_URL=redis://redis:6379/0
  db:
    image: postgres:13
    container_name: courseswap_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: courseswap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: courseswap_redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
